services:
  adminpls:
    build: .
    image: adminpls:v1
    container_name: adminpls
    hostname: adminpls
    restart: always
    ports:
      - 8123:5000
    environment:
      - TZ=America/Guayaquil
      - APP_SETTINGS_MODULE=config.prod
    # networks setup depends on intercomm between other container stacks. Depends on declaration near the end of this file. This is optional
    # it's required if you setup a proxy reverse like nginx or connection to a DB inside the same machine
    # networks:
    #   master_network: # this is the network name

  plsworker:
    build: .
    image: adminpls:v1
    container_name: plsworker
    hostname: plsworker
    restart: always
    environment:
      - TZ=America/Guayaquil
      - APP_SETTINGS_MODULE=config.prod
    entrypoint: celery -A app.scheduler.celery worker --loglevel=info -E --detach --pidfile=''
    depends_on: 
      - redis
      - adminpls

  plsbeat:
    build: .
    image: adminpls:v1
    container_name: plsbeat
    hostname: plsbeat
    restart: always
    environment:
      - TZ=America/Guayaquil
      - APP_SETTINGS_MODULE=config.prod
    entrypoint: celery -A app.scheduler.celery beat --loglevel=info --detach --pidfile=''
    depends_on: 
      - redis
      - adminpls

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
#    networks:
#      - master_network

# setup other packages/services like db, proxy reverse, etc.
# setup network if required look at the "networks" section above
# networks:
#   master_network:
#     external: True